"""Stable public API for the standalone fhiratwill core library."""

from fhiratwill.assembly import (
    AssembledBundle,
    AssemblyAction,
    AssemblyNote,
    assemble_bundle,
    resolve_datatype,
)
from fhiratwill.binding import (
    BindingAction,
    BindingCoverage,
    BindingNote,
    BoundBundle,
    ConceptPack,
    bind_bundle,
    load_concepts,
)
from fhiratwill.context import (
    PlanNote,
    PreflightCheck,
    PreflightReport,
    PreflightStatus,
    ResourceReader,
    SubjectContext,
    rebind_bundle,
    run_preflight,
)
from fhiratwill.errors import (
    FhiratwillError,
    TargetUnavailableError,
    TerminologyError,
    TerminologyUnavailableError,
    UnknownValueSetError,
)
from fhiratwill.planning import PlanStepStatus, WritePlan, WriteStep, compile_write_plan
from fhiratwill.targets import (
    GENERIC_FHIR_TARGET,
    FailurePolicy,
    GenericFhirTarget,
    TargetDescriptor,
)
from fhiratwill.terminology import (
    CodeSystemVersion,
    Coding,
    ExpansionResult,
    LookupResult,
    SubsumesResult,
    SubsumptionOutcome,
    TerminologyClient,
    TerminologyHealth,
    TranslateMatch,
    TranslateResult,
    ValidateCodeResult,
)

__version__ = "0.1.0"

__all__ = [
    "GENERIC_FHIR_TARGET",
    "AssembledBundle",
    "AssemblyAction",
    "AssemblyNote",
    "BindingAction",
    "BindingCoverage",
    "BindingNote",
    "BoundBundle",
    "CodeSystemVersion",
    "Coding",
    "ConceptPack",
    "ExpansionResult",
    "FailurePolicy",
    "FhiratwillError",
    "GenericFhirTarget",
    "LookupResult",
    "PlanNote",
    "PlanStepStatus",
    "PreflightCheck",
    "PreflightReport",
    "PreflightStatus",
    "ResourceReader",
    "SubjectContext",
    "SubsumesResult",
    "SubsumptionOutcome",
    "TargetDescriptor",
    "TargetUnavailableError",
    "TerminologyClient",
    "TerminologyError",
    "TerminologyHealth",
    "TerminologyUnavailableError",
    "TranslateMatch",
    "TranslateResult",
    "UnknownValueSetError",
    "ValidateCodeResult",
    "WritePlan",
    "WriteStep",
    "__version__",
    "assemble_bundle",
    "bind_bundle",
    "compile_write_plan",
    "load_concepts",
    "rebind_bundle",
    "resolve_datatype",
    "run_preflight",
]
